model_params:
  name: 'CSVAE'
  in_channels: 3
  num_classes: 40
  latent_dim: 128

exp_params:
  name: 'CSVAE'
  dataset: celeba
  data_path: "../../../../../../miniscratch/canturks/data/"
  img_size: 64
  batch_size: 128 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "CSVAE"
  manual_seed: 1265
