model_params:
  name: 'InfoVAE'
  in_channels: 3
  latent_dim: 3
  reg_weight: 110  # MMD weight
  kernel_type: 'imq'
  alpha: -9.0     # KLD weight
  beta: 10.5      # Reconstruction weight

exp_params:
  dataset: wikiart
  data_path: "../../../../../../miniscratch/canturks/data/"
  img_size: 64
  batch_size: 256 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0]
  max_epochs: 50
  gradient_clip_val: 0.8

logging_params:
  save_dir: "logs/"
  name: "InfoVAE (WikiArt, LD=3, LR=0.001)"
  manual_seed: 1265




