model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 40

exp_params:
  dataset: mnist
  data_path: "../../../../../../miniscratch/canturks/data/"
  img_size: 28
  batch_size: 256 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [0]
  max_epochs: 50

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE (MNIST, LD=40, LR=0.001)"
  manual_seed: 1265
